api:
  port: 8081
serviceDiscovery:
  name: metadata
  consul:
    address: http://consul-server.consul.svc.cluster.local:8500
database:
  host: mysql.database.svc.cluster.local
  port: 3306
  user: root
  password: password
  dbname: movieapp